# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XlGZHNl3jRuharwnXsMi_7d8RMrhsWlc
"""

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np


fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')

O = np.array([0,0,0]).reshape((3,1))
V = np.array([2,-1,-2]).reshape((3,1))
norm_V = numpy.linalg.norm(V)
U = V/norm_V


OV = V-O
OU = U-O

L_OV = np.empty((2,3),float)
L_OV[0,:] = V[:,0]
L_OV[1,:] = O[:,0]

L_OU = np.empty((2,3),float)
L_OU[0,:] = U[:,0]
L_OU[1,:] = O[:,0]


plt.plot(L_OV[:,0],L_OV[:,1],L_OV[:,2],'r',label="OV")
plt.plot(L_OU[:,0],L_OU[:,1],L_OU[:,2],'y',label="OU")

ax.scatter(V[0],V[1],V[2],'o')
ax.scatter(U[0],U[1],U[2],'o')
ax.scatter(0,0,0, 'o')

ax.text(2,-1,-2, "V", color='blue')
ax.text(2/3,-1/3,-2/3, "U", color='blue')
ax.text(0,0,0, "O", color='blue')


plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend(loc='best');plt.grid()
plt.title('Unit vector U along vector V')
plt.show()

print('Vector V is :\n',OV)
print('Unit Vector U along vector V is :\n',OU)