# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WrLGtNVO6yAd4Qlu-YZSt6jaIId1M2_a
"""

import numpy as np
import matplotlib.pyplot as plt

t = np.linspace(-3,5,100)

y=[]

for i in t:
  if (i>=-2 and i<-1):
    y.append(2)
  elif (i>=-1 and i<2): 
    y.append(-1) 
  else:
    y.append(0)

plt.plot(t,y)
plt.xlabel('t')
plt.ylabel('y(t)')
plt.grid()
plt.title('output')
plt.show()